monitor:
    brokers:
        - 10.200.10.1:9092
    # Check every 10s
    check_interval: 10
    consumer_groups:
        topic1:
            group_name: group_id_1
        topic2:
            group_name: group_id_2
    statsd:
        host: 10.200.10.1
        port: 8125
        prefix: lagmonitor
