monitor:
    brokers:
        - kafka:9092
    # Check every 10s
    check_interval: 10
    consumer_groups:
        topic1:
            group_name: group_id_1
        topic2:
            group_name: group_id_2
    statsd:
        host: kafka
        port: 8125
        prefix: lagmonitor
